### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'img/time.png'

### ISSUE THREAD

**Issue by dbeyr** [aforizm/avatar-change-time#2]
Что я делаю не так?Traceback (most recent call last):
  File "main.py", line 17, in <module>
    change_img()
  File "/Users/IlyaMacBook/Desktop/Code/avatar-change-time-master/generate_time_images.py", line 25, in change_img
    row.save(f'img/time.png', "PNG")
  File "/Users/IlyaMacBook/Library/Python/3.7/lib/python/site-packages/PIL/Image.py", line 2004, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'img/time.png'

**Comment by aforizm** [comment]
Скорее отсутсвует папка с названием img, попробуй создать ее в корневом каталоге

**Comment by dbeyr** [comment]
> Скорее все отсутствует папка с названием img, попробуй создать ее в корневом каталоге
> 
> **upd**: поправил код, теперь картинка будет сохраняться в корневом каталоге

круть! Спасибо, поменял часовой пояс и сменил на Бангкок))

**Comment by aforizm** [comment]
бесплатный хостинг есть на Pythonanywhere.com, и есть ещё heroku.com

**Comment by islomferg** [comment]
Здравствуйте а как поменять Город\Страну в скрипте пишу Tashkent пишет NameError: name 'TASHKENT' is not defined

**Comment by p152** [comment]
> бесплатный хостинг есть на Pythonanywhere.com, и есть ещё heroku.com

Здравствуйте, как можно запустить на Heroku? там же надо ввести номер и код подтверждение.
